### PR TITLE
Optimization of unused code in command parsing [resubmitted]

### LINKED ISSUE #115: Optimization of unused code in command parsing readConfig()
Not a big deal, but some code can be left off according to compilation options. (Will update with reference to PR).

### PR DESCRIPTION
**Pull request by GioCC**
## Description of changes

Fixes #115
Replaces PR #116 (tied to wrong branch)

### CODE REVIEW

**Review by DocMoebiuz — COMMENTED** [review]
Thanks for this proposal.

I just wondered: It would make sense to enclose the entire "case"-branch with the #if #endif, don't you think?

We would not have to deal with the same
```
#else
      strtok_r(NULL, ":", &p); // skip unmanaged command
#endif
```
because that would be done by the default case then.

**Review by DocMoebiuz — CHANGES_REQUESTED** [review]
see my last comment.

**Comment by GioCC** [comment]
Yes, of course it makes sense. Silly me :) 
I'll change it right away.

**Review by DocMoebiuz — APPROVED** [review]
YEAH!

**Pull request merged**
