### PR TITLE
Clean up version number before build

### LINKED ISSUE #125: Make version number handling more robust
* Don't require a "v" in front
* Strip off leading and trailing periods

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #125

* Strip any leading "v" off the version
* Strip any leading or trailing dots off the version

### CODE REVIEW

**Comment by neilenns** [comment]
This is part 1. Part 2 will be done over in the MobiFlight-Connector repo on the script that pulls the builds.

**Comment by MobiFlight-Admin** [comment]
We can update the readme text then:

Click Choose a tag and create a new version tag, e.g. v1.14.0. Note that this must include the v at the front for various release scripts to work correctly.

**Review by MobiFlight-Admin — APPROVED** [review]
Thanks!

**Comment by neilenns** [comment]
@MobiFlight-Admin Good catch, readme updated.

**Pull request merged**
