### PR TITLE
Clean up the build scripts

### LINKED ISSUE #235: Clean up the build scripts
While working on some build process stuff for one of my private firmware builds I discovered a few things that need cleaning up:

1. Need to explicitly define `python_version` when downloading python. It should be `3.9`.
2. The caching mechanism isn't right, see https://github.com/platformio/platformio-docs/blob/develop/integration/ci/github-actions.rst
3. No need to do `python -m pip install --upgrade pip` before doing the pip install.

Example of these changes in action is at https://github.com/neilenns/Collins-FMS-3000-Firmware/tree/main/.github/workflows

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #235

## Description of changes

* Explicitly set the python version to use
* Add proper caching for PlatformIO

Build time without cache: 7 minutes 13 seconds
Build time with cache: 3 minutes 34 seconds

### CODE REVIEW

**Comment by neilenns** [comment]
First run of this PR shows no cache was present:

```
Cache not found for input keys: Linux-pio
```

Second run of this PR shows the cache being used:

```
Received 0 of 1725[13](https://github.com/MobiFlight/MobiFlight-FirmwareSource/actions/runs/6878073505/job/18706927963#step:4:14)376 (0.0%), 0.0 MBs/sec
Received 50331648 of 172513376 (29.2%), 23.8 MBs/sec
Received [14](https://github.com/MobiFlight/MobiFlight-FirmwareSource/actions/runs/6878073505/job/18706927963#step:4:15)3[15](https://github.com/MobiFlight/MobiFlight-FirmwareSource/actions/runs/6878073505/job/18706927963#step:4:16)3248 of 172513376 (83.0%), 45.2 MBs/sec
Cache Size: ~[16](https://github.com/MobiFlight/MobiFlight-FirmwareSource/actions/runs/6878073505/job/18706927963#step:4:17)5 MB (172513376 B)
/usr/bin/tar -xf /home/runner/work/_temp/81ee234b-19b0-4657-b240-b4b7daa7f1c5/cache.tzst -P -C /home/runner/work/MobiFlight-FirmwareSource/MobiFlight-FirmwareSource --use-compress-program unzstd
Cache restored successfully
Cache restored from key: Linux-pio
```

**Comment by neilenns** [comment]
Even with the cache being used I still see the pico-sdk getting cloned. I assume that is because it uses a different mechanism than other dependencies (cloned from a github repo instead of referenced from the platformio library). pico-sdk cloning is what is driving our long build times :(

**Comment by neilenns** [comment]
Found a thread about caching toolchains: https://community.platformio.org/t/caching-platformio-external-in-libs-gitlab-ci/12160/2, trying that.

**Review by DocMoebiuz — APPROVED** [review]
Thanks!

**Pull request merged**
