### PR TITLE
Improve getting correct device infos for connector from Mega

### LINKED ISSUE #200: Mega get's sometimes not properly identified
Sometimes the Mega (and I expect the same for the Uno) get's not properly identified from the connector. That means that:
* eeprom config
* serial number
* devices
can be misread (not always). This was found from @Jaime Leon and is reported on Discord.
He found also, that all switches put into OFF position helped for properly booting.

It seems that this behaviour is related to the initilisation of the buttons. Every button is initilised woith `1`, so after startingup for each ON button a status change is detected and a serial message is generated. For multiple buttons multiple messages are generated. As this comes directly after the GUI has connected (reset via DTR for Mega/Uno) and the connector asks for the board info's, it seems that this disturbs the correct identification of the aboved mentioned infos.
A first test from Jaime Leon of initialisation the buttons with the actual status solved this problem. As no status change is identified on startup no serial message gets generated.

The same applies to:
* input shifter
* multiplexer
* analog in
 For analog in this is fixed by PR #199 where the average buffer is filled on startup. For the input shifter and buttons I have already prepared the changes.
For the multiplexer I would like to ask @GioCC to prepare the changes as I am unsure what the best way would be.

### PR DESCRIPTION
**Pull request by elral**
## Description of changes
Buttons and input shifters are initialized with the actual status of inputs.
This avoids serial messages an startup due to changed status of inputs in case they are closed (ON).

Fixes #200

### CODE REVIEW

**Review by DocMoebiuz — APPROVED** [review]
Thanks. That was fast.

**Comment by GioCC** [comment]
Not really sure if duplicating the shift register poll in the constructor is nice; also it's not consistent with the approach used for analog inputs (use the existing function by adding an argument that says whether the change of value should trigger events).
I'd like to change that while adding the multiplexer part (that should complete this fix).

**Comment by elral** [comment]
> Not really sure if duplicating the shift register poll in the constructor is nice; also it's not consistent with the approach used for analog inputs (use the existing function by adding an argument that says whether the change of value should trigger events). I'd like to change that while adding the multiplexer part (that should complete this fix).

Yeah, maybe you are right that doubling is not the best solution. I thought about this but came to the conclusion that it is less code which gets doubled compared to readability. And looking on all functions it is tripled (I didn't want to change the `update()` function).
I will have a closer look if/how it can be simplified/harmonized.

**Comment by GioCC** [comment]
I have included those changes with the multiplexer mods that I will be posting shortly, you can have a look at them and see if they suit you.

**Pull request merged**
