### PR TITLE
Increase nano max analog count to 8

### LINKED ISSUE #241: Increase the max number of analog pins on the Nano to 8
This will allow pins A6 and A7 to be used along with all the rest at the same time.

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #241

Increase the max number of analog pins on the Nano to 8, to account for A6 and A7 also being options.

### CODE REVIEW

**Comment by elral** [comment]
How to we handle the increase of analog inputs for the ProMicro?
In a separate PR or within this one?

**Comment by neilenns** [comment]
I wasn't aware there was a request to do that. Is there a bug logged?

**Comment by elral** [comment]
Jaime brought this topic up in a discord channel and opened the issue [#1228](https://github.com/MobiFlight/MobiFlight-Connector/issues/1228).
8 (or 9) analog inputs means 232 (261) bytes are required from the device buffer. This one is 286 (440) bytes in size. At least for the Nano very limited and depending on devices not all can be configured.
Freeing up the name buffer would really help ;)

numbers in () are for the ProMicro

**Comment by neilenns** [comment]
Argh, my bad. I forgot there was already an issue open for this :(

I'll close this PR and the issue I opened and just leave Jaime's open for you to do.

**Pull request closed without merging**
